### ISSUE TITLE
Discover "aces-dev".

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#3]
Hi,

Instead of polluting #1, I'm creating a new thread to discuss the discovery repo I have been poking at lately: https://github.com/colour-science/discover-aces-dev

It is an experiment at this stage, but the code walks through https://github.com/ampas/aces-dev/tree/master/transforms/ctl, discovers and classifies all the relevant CTL transforms and transform pairs.

My naive hope is that we might eventually be able to use that process to automatically build the core ACES config that matches `aces-dev` without too much code.

A direct benefit is that it enforces things to be clean on the CTL side, and while implementing the discovery code, [a few things surfaced](https://github.com/ampas/aces-dev/issues/118) that I hope we will be able to resolve in a timely fashion.

![image](https://user-images.githubusercontent.com/99779/84887097-6402e000-b0e9-11ea-9c75-2a71bac8ba30.png)

Note that I cheated for the LMTs, they should not be visible because their source and target are AP0. I also culled most of the Alexa transforms, the ridiculous number of them was blowing up the graph.

Cheers,

Thomas

**Comment by michdolan** [comment]
I think the challenge with this will be generating the OCIO v2 transforms from the underlying CTL algorithms (wherever possible) instead of generating LUTs through `ctlrender`. How do we determine which transforms must be generated from CTL, and which can be created natively with OCIO? I suspect we'll end up writing functions to standardize common components of ACES with OCIO which would be a bit more manually tuned. Up for discussion though.

At the very least, this discovery code serves to outline the scope of the config, and even to validate its complete representation in CI, which could be useful for detecting when ACES has changed and something is missing.

**Comment by KelSolaar** [comment]
> How do we determine which transforms must be generated from CTL, and which can be created natively with OCIO?

My assumption is that any single of the edges in the graph above has a corresponding OCIO transform, if so, then creating the config is really a matter of mapping them together.

**Comment by KelSolaar** [comment]
I think we can close that one now!
