### ISSUE TITLE
ACES Whitepoint is not D60

### ISSUE THREAD

**Issue by KelSolaar** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#98]
Hi,

I noticed that last year but forgot to address it:

```python
    name = "AP0_to_Gamma2.2_AP1-Texture"
    clf_transform_id = format_clf_transform_id(FAMILY, GENUS, name, VERSION)
    filename = output_directory / clf_basename(clf_transform_id)
    clf_transforms[filename] = generate_clf_transform(
        filename,
        [
            matrix_RGB_to_RGB_transform("ACES2065-1", "ACEScg"),
            gamma_transform(2.2),
        ],
        clf_transform_id,
        "AP0 to Gamma 2.2 AP1 - Texture",
        "ACES2065-1",
        "2.2 gamma-corrected AP1 primaries, D60 white point", <<<---
    )
```

The ACES whitepoint is not D60, it is close but not quite like it: https://docs.acescentral.com/tb/white-point

**Comment by doug-walker** [comment]
If we do make a change, I would use "ACES D60 white point" rather than "approximately D60 white point" or something like that.

A delta u'v' of 0.00008 is well below the visual threshold.  For 99% percent of ACES users, the difference does not matter and raising the issue may cause confusion and doubt, more than help.

After all, the industry uses [0.3127, 0.3290] for D65, which differs from the precise value by a similar amount that the ACES whitepoint differs from the precise D60.  Referring to Rec.709 as "approximately D65" would cause a lot of confusion and it's not clear who would really benefit.

**Comment by doug-walker** [comment]
This is now implemented.
